### ISSUE TITLE
Add Github validation action

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.resources#16]
Would be nice to have a Github verification build in additional to the sometimes very slow Jenkins servers.

@mickaelistria or @laeubi WDYT?

**Comment by laeubi** [comment]
Give it a try ;-)

**Comment by mbarbero** [comment]
Currently, GitHub actions are free (unlimited) for public repos:

> GitHub Actions usage is free for both public repositories and self-hosted runners

(https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions)

Beware that this may change at any time. We recommend projects to carefully ponder this. We're witnessing a trend of diminishing free resources for OSS projects in the last couple of years, most of the time with very short notice:

* [Docker Hub pull rate limits](https://www.docker.com/blog/what-you-need-to-know-about-upcoming-docker-hub-rate-limiting/)
 
* [JFrog terminating BinTray and others](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). 

* [Travis CI removing almost all free resources to OSS projects](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) and https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works
 
We often hear that any changes to CI is pain for developers. Moving from Jenkins to GH actions, and maybe to something else when GH actions will not be free (or unlimited enough) anymore may be an acceptable cost/risk to projects. Or not.

**Comment by laeubi** [comment]
There is no such thing as unlimited computer power and in the end we are all limited :-)

https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits

**Comment by iloveeclipse** [comment]
Can someone tell what is an API request and if that is used by us?
The limits are applied per organization or per repository? 
So if that per organization, https://github.com/eclipse-pde and https://github.com/eclipse-jdt should **not** be same organization, right? Or eclipse.org is somehow the common organization? 
The "interesting" limits are for 1000 API requests per hour, 20 concurrent jobs.

**Comment by laeubi** [comment]
> So if that per organization, https://github.com/eclipse-pde and https://github.com/eclipse-jdt should **not** be same organization

That's how i understand this, a normative answer can only be given by github-support I think

> The "interesting" limits are for 1000 API requests per hour, 20 concurrent jobs.

If anyone is interested at tycho I have set it up that oboslete jobs are canceled:

https://github.com/eclipse/tycho/blob/b1b992c877026f9d0903f58011835d7dc4996559/.github/workflows/maven.yml#L5-L7

beside that github recommends to enable parallel builds (`-T1C`) and caches to cut down the time of an individual run. At tycho I have never noticed any rate limiting (yesterday a job was canceld because it seems to run for more than a few hours because of networking problems.

In the wend, we can try that out, no one claims that we want to **replace** eclipse CI, but for example the GH action can run a fast compile check and the integration test can run overnight at eclipse-infra... in the end it is also possible to connect custom runners if anyone like to spend more processing power...

**Comment by vogella** [comment]
First version of Github action merged not yet including the test execution. Please feel free to enhance. https://github.com/eclipse-platform/eclipse.platform.resources/pull/18

**Comment by laeubi** [comment]
It seems one of the project leads need to enable gh actions for this repository.

**Comment by vogella** [comment]
@laeubi I don't see this option in the UI @akurtakov do you see it?

**Comment by akurtakov** [comment]
We don't have such permissions. Requested here https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1094
