### ISSUE TITLE
Add Preference to Turn Off Warning-Check for Project Specific Encoding

### ISSUE THREAD

**Issue by ingomohr** [eclipse-platform/eclipse.platform.resources#166]
Eclipse 2022-06 introduced a check that produces a warning "No explicit project encoding" when a project has no explicit encoding set.

Although this imho is a good idea in general, it should be possible to turn the check off.

Motivation:
We have hundreds of projects that all take-over the encoding from the workspace preferences (which is configured automatically via Oomph). We want to be free to decide whether or not we add the encoding also to each of the project.

**Comment by Bananeweizen** [comment]
Your explanation doesn't make sense to me, since it totally doesn't tell _why you can't_ change the setting. It just says "We want", without any actual reasoning. That warning has a quickfix and is therefore easy to apply in minutes, even on large workspaces and multi repository setups (I've done it myself, too). This setting is also meant as a counter measure to ease the transition to Java 18. That one has a different default encoding on Windows than all Java versions before, and therefore people will easily have different build results without very explicitly specifying encodings in their Maven POMs and project settings.

**Comment by ingomohr** [comment]
Sorry, that quickfix just applies the encoding settings to the project files. i.e. you end up having the same file in each of your projects.

If you don't want to have that file in all of your projects because the Eclipse workspace settings already specifiy the desired encoding (and Java 18 is not the near future in your company yet), you should be able to both just specify the encoding in your workspace settings and don't have warnings in your project.

* Good tools provide means to fulfill your process. They are not meant to enforce their own prociess on your teams.
    * in this case: Eclipse should not force you to add clutter to all of your projects
* Project specific settings in Eclipse are designed to specificy project settings that don't match your workspace settings default.
   * We should stick to the design - or otherwise get rid of the workspace settings entire
   * It's bad design to have a little bit of _this_ approach and a little bit of _that_ approach.

**Comment by merks** [comment]
I agree it seems odd to have a warning that you can't suppress.   It should probably be treated like this warning about unknown natures:

![image](https://user-images.githubusercontent.com/208716/175890131-59ec10f2-7aa2-49eb-afe1-e0c3188828a3.png)

**Comment by iloveeclipse** [comment]
> I agree it seems odd to have a warning that you can't suppress.

Sure you can. Just set explicit project encoding.

> and Java 18 is not the near future in your company yet

The future may be faster as you may imagine.

Regarding not reporting this warning: well, you will set this new preference, a project will be opened in a workspace with no Oomph configured, some data will be changed using wrong encoding, and you will report a bug for Eclipse that it didn't warned you doing bad things.

But if you think it is crucial for your organization to have this preference, feel free to contribute this (Ed proposed good place for the preference) - Eclipse is open source project driven in many parts by user contributions.

**Comment by merks** [comment]
@ingomohr The platform has a nice Oomph setup too, so it shouldn't be hard to contribute such a preference...

**Comment by eum2o** [comment]
> Project specific settings in Eclipse are designed to specify project settings that don't match your workspace settings default.

This. 

> Sure you can. Just set explicit project encoding.

We have hundreds of projects - all without project-specific settings. Currently, if we want to change Java compiler settings, we only have to update the Eclipse preferences (e.g. in Oomph), and the change is applied to all projects indirectly.

Now you're suggesting introducing project-specific settings to all projects. In the future, when we want to change Java compiler settings, we have to update hundreds of places instead of only one place. I don't like this suggestion. 

In my opinion, this new feature is buggy because it adds warning markers to valid projects. It's only complete when the new warning can be configured in the preferences (consistently to other checks).

**Comment by ingomohr** [comment]
If that ok w/ you all, I'll work on an severity-configuration integration as @merks suggested.

**Comment by ingomohr** [comment]
Hi all,

I found the following commit which introduced the feature

```
Bug 479451 - Warning for projects without explicit encoding

Add a warning marker to projects without explicit encoding. The warning
is meant to encourage setting an explicit encoding to all projects, so
that the workspace default encoding can change without breaking
projects.

Change-Id: Id112603856a334447d5d504adc874f769a1daa80
Signed-off-by: Simeon Andreev <simeon.danailov.andreev@gmail.com>
Reviewed-on: https://git.eclipse.org/r/c/platform/eclipse.platform.resources/+/192052
Tested-by: Platform Bot <platform-bot@eclipse.org>
Reviewed-by: Andrey Loskutov <loskutov@gmx.de>
```

**Question**: Do I have to still have to work w/ Bugzilla and Gerrit for this one? Or what's the contribution workflow right now?
Thanks in advance!

**Comment by merks** [comment]
You need to commit to a topic branch of your fork of this repository and create a pull request from that as described here:

https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md#recommended-workflow

Personally I don't do it exactly like that.  I always clone the original github repo and then I create an extra remote that is hooked up to my fork:

![image](https://user-images.githubusercontent.com/208716/177031465-cf8a34d4-2a60-4609-a0bc-0a8efbdbe8bc.png)

Then I create a new topic branch and when I push it the first time, I specify to use the "merks" remote so that it goes into my fork.

So no, you don't use Bugzilla (replaced by Issues) nor Gerrit (replaced by Pull Requests).

**Comment by ingomohr** [comment]
#### Suggestion of Change
Hi @merks, if I understood you correctly, this could be the intregration to the Workspace preference page.

<img width="458" alt="Screenshot 2022-07-03 at 11 02 15" src="https://user-images.githubusercontent.com/2838592/177032870-392cf73c-38c7-4880-8cb7-38055d0eabe4.png">

Does that fit for you? (I forked the UI repo for the change).

**Comment by merks** [comment]
It's the right place.  

I'm not sure the word `unknown` gives quite the right idea.  Perhaps `Report missing project-specific encoding as:` though more accurately `Report missing project-specific project encoding as:` but that's kind of unwieldy.  Or `Report missing project encoding as:` or `Report unspecified project encoding as:`.

@mickaelistria @iloveeclipse Maybe you guys have an opinion on the wording?

**Comment by iloveeclipse** [comment]
Report missing project encoding sound good

**Comment by ingomohr** [comment]
![image](https://user-images.githubusercontent.com/2838592/177980088-1b5a8c96-0fc4-4e4d-a66a-9ec8fd19d8e7.png)

Thanks for your feedback, @merks and @iloveeclipse! This is what it looks now. I'll be finishing up the impl (hopefully) today and then create the PRs back to the original Eclipse repos I forked from.

**Comment by ingomohr** [comment]
@merks I added PR #167 for this issue. In it I left some comments on what I think I'd like to finalize. Maybe you (or somebody else - any feedback/help is very welcome!) can have a look at it. Thank you! :)

**Comment by ingomohr** [comment]
@merks Since pull request #167 had been merged: Is there anything else to do for this issue? Or should I close it?

**Comment by ingomohr** [comment]
💡 Referenced UI issue for this is https://github.com/eclipse-platform/eclipse.platform.ui/issues/198

(I added the link here b/c I couldn't find it in a quick way looking at this issue).

**Comment by merks** [comment]
I think it's done.  The UI part is a separate issue because it's a different git repo...

**Comment by ingomohr** [comment]
Ok, thanks for the quick response, @merks.
